language: "perl"

perl:
  - "5.16"
  - "5.14"

services:
  - mysql

jdk:
  - oraclejdk8
  
before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-production.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-hive
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-taxonomy
    - git clone -b bioperl-release-1-6-1 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
    - travis_wait cpanm --installdeps --with-recommends --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n DBD::mysql DBD::SQLite

before_script:
    - sleep 10
    
script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      secure: OdwEI3TMYZMTEsg6UqwYYW0WRUBOWsbsmv0W1ccnwGgZmTKGIFTfIwCeNXx75pJruPj0Vj2yLRAXGUMXR5jZg1H8NqRKNDpiUTU79AQ6COrraFNKZV4f3fvKldNccH9JMhJCttfO4/+o3UcOEGX5uBHsdrYHw9LigCXHqM0L3G+evpGass498jrbCuOhaT2r2ELLE/8svqRJ4Q74ylIfe95K5hhoSRF9YaD2pqJor8CbTeroQTlfaDkwJKmDvOcGxL9BfvDKqXu+f9JzSdaAT1+RjuCJzumkRucn35kAXmYJ7sF0mA5ehb20zBIjvzCQt9NO29OrP6p7tztV8GVRaFzFDDkc4vUYRWVvTkxVxKff65vpdv51qtsKwLEPHmqrE8YW0Xfe/hw7R2QZmq8yqG0SGcUzAYXlZctx/2VPaj7sV7jNKwKGP3wISFy09EsjblCNte7uK4AmjzFsrwYYct77fBDlEdm7rgcksbo6Iq9ESvuQsam7D8loAnnpXzQpDzlnDT7QLDNPEm+Lvnp+RZle4Ukapn754hQLDAv4adckmzo0ofPJtdFIue+UEIBlIKDkFtdsTDxMyvl8yKWcetNizOYg6xTDYc4cpzu8A+/LEmt7In9ioih7+jKuTWp3usT6KVGTKsUkRi1TpoQZeqRNoKJuS+di7HRj6y9gMZw=
    on_failure: change
